site_name: Tanaguru Rules RGAA3
pages:
- Home: index.md
- Images:
  - Rule 1.1.1: Rule-1-1-1.md
  - Rule 1.1.2: Rule-1-1-2.md
  - Rule 1.1.3: Rule-1-1-3.md
  - Rule 1.1.4: Rule-1-1-4.md
  - Rule 1.2.1: Rule-1-2-1.md
  - Rule 1.2.2: Rule-1-2-2.md
  - Rule 1.2.3: Rule-1-2-3.md
  - Rule 1.2.4: Rule-1-2-4.md
  - Rule 1.2.5: Rule-1-2-5.md
  - Rule 1.3.1: Rule-1-3-1.md
  - Rule 1.3.2: Rule-1-3-2.md
  - Rule 1.3.3: Rule-1-3-3.md
  - Rule 1.3.4: Rule-1-3-4.md
  - Rule 1.3.5: Rule-1-3-5.md
  - Rule 1.3.6: Rule-1-3-6.md
  - Rule 1.3.7: Rule-1-3-7.md
  - Rule 1.3.8: Rule-1-3-8.md
  - Rule 1.3.9: Rule-1-3-9.md
  - Rule 1.3.10: Rule-1-3-10.md
  - Rule 1.4.1: Rule-1-4-1.md
  - Rule 1.4.2: Rule-1-4-2.md
  - Rule 1.4.3: Rule-1-4-3.md
  - Rule 1.4.4: Rule-1-4-4.md
  - Rule 1.4.5: Rule-1-4-5.md
  - Rule 1.4.6: Rule-1-4-6.md
  - Rule 1.4.7: Rule-1-4-7.md
  - Rule 1.4.8: Rule-1-4-8.md
  - Rule 1.4.9: Rule-1-4-9.md
  - Rule 1.5.1: Rule-1-5-1.md
  - Rule 1.5.2: Rule-1-5-2.md
  - Rule 1.6.1: Rule-1-6-1.md
  - Rule 1.6.2: Rule-1-6-2.md
  - Rule 1.6.3: Rule-1-6-3.md
  - Rule 1.6.4: Rule-1-6-4.md
  - Rule 1.6.5: Rule-1-6-5.md
  - Rule 1.6.6: Rule-1-6-6.md
  - Rule 1.6.7: Rule-1-6-7.md
  - Rule 1.6.8: Rule-1-6-8.md
  - Rule 1.7.1: Rule-1-7-1.md
  - Rule 1.7.2: Rule-1-7-2.md
  - Rule 1.7.3: Rule-1-7-3.md
  - Rule 1.7.4: Rule-1-7-4.md
  - Rule 1.7.5: Rule-1-7-5.md
  - Rule 1.7.6: Rule-1-7-6.md
  - Rule 1.7.7: Rule-1-7-7.md
  - Rule 1.8.1: Rule-1-8-1.md
  - Rule 1.8.2: Rule-1-8-2.md
  - Rule 1.8.3: Rule-1-8-3.md
  - Rule 1.8.4: Rule-1-8-4.md
  - Rule 1.8.5: Rule-1-8-5.md
  - Rule 1.8.6: Rule-1-8-6.md
  - Rule 1.9.1: Rule-1-9-1.md
  - Rule 1.9.2: Rule-1-9-2.md
  - Rule 1.9.3: Rule-1-9-3.md
  - Rule 1.9.4: Rule-1-9-4.md
  - Rule 1.9.5: Rule-1-9-5.md
  - Rule 1.9.6: Rule-1-9-6.md
  - Rule 1.10.1: Rule-1-10-1.md
  - Rule 1.10.2: Rule-1-10-2.md
  - Rule 1.10.3: Rule-1-10-3.md
  - Rule 1.10.4: Rule-1-10-4.md
  - Rule 1.10.5: Rule-1-10-5.md
- Frames:
  - Rule 2.1.1: Rule-2-1-1.md
  - Rule 2.2.1: Rule-2-2-1.md
- Colours:
  - Rule 3.1.1: Rule-3-1-1.md
  - Rule 3.1.2: Rule-3-1-2.md
  - Rule 3.1.3: Rule-3-1-3.md
  - Rule 3.1.4: Rule-3-1-4.md
  - Rule 3.1.5: Rule-3-1-5.md
  - Rule 3.1.6: Rule-3-1-6.md
  - Rule 3.2.1: Rule-3-2-1.md
  - Rule 3.2.2: Rule-3-2-2.md
  - Rule 3.2.3: Rule-3-2-3.md
  - Rule 3.2.4: Rule-3-2-4.md
  - Rule 3.2.5: Rule-3-2-5.md
  - Rule 3.2.6: Rule-3-2-6.md
  - Rule 3.3.1: Rule-3-3-1.md
  - Rule 3.3.2: Rule-3-3-2.md
  - Rule 3.3.3: Rule-3-3-3.md
  - Rule 3.3.4: Rule-3-3-4.md
  - Rule 3.4.1: Rule-3-4-1.md
  - Rule 3.4.2: Rule-3-4-2.md
  - Rule 3.4.3: Rule-3-4-3.md
  - Rule 3.4.4: Rule-3-4-4.md
- Multimedia:
  - Rule 4.1.1: Rule-4-1-1.md
  - Rule 4.1.2: Rule-4-1-2.md
  - Rule 4.1.3: Rule-4-1-3.md
  - Rule 4.2.1: Rule-4-2-1.md
  - Rule 4.2.2: Rule-4-2-2.md
  - Rule 4.2.3: Rule-4-2-3.md
  - Rule 4.3.1: Rule-4-3-1.md
  - Rule 4.3.2: Rule-4-3-2.md
  - Rule 4.4.1: Rule-4-4-1.md
  - Rule 4.5.1: Rule-4-5-1.md
  - Rule 4.5.2: Rule-4-5-2.md
  - Rule 4.6.1: Rule-4-6-1.md
  - Rule 4.6.2: Rule-4-6-2.md
  - Rule 4.7.1: Rule-4-7-1.md
  - Rule 4.7.2: Rule-4-7-2.md
  - Rule 4.8.1: Rule-4-8-1.md
  - Rule 4.8.2: Rule-4-8-2.md
  - Rule 4.9.1: Rule-4-9-1.md
  - Rule 4.9.2: Rule-4-9-2.md
  - Rule 4.10.1: Rule-4-10-1.md
  - Rule 4.10.2: Rule-4-10-2.md
  - Rule 4.11.1: Rule-4-11-1.md
  - Rule 4.11.2: Rule-4-11-2.md
  - Rule 4.12.1: Rule-4-12-1.md
  - Rule 4.12.2: Rule-4-12-2.md
  - Rule 4.13.1: Rule-4-13-1.md
  - Rule 4.13.2: Rule-4-13-2.md
  - Rule 4.14.1: Rule-4-14-1.md
  - Rule 4.14.2: Rule-4-14-2.md
  - Rule 4.15.1: Rule-4-15-1.md
  - Rule 4.15.2: Rule-4-15-2.md
  - Rule 4.16.1: Rule-4-16-1.md
  - Rule 4.16.2: Rule-4-16-2.md
  - Rule 4.17.1: Rule-4-17-1.md
  - Rule 4.18.1: Rule-4-18-1.md
  - Rule 4.19.1: Rule-4-19-1.md
  - Rule 4.20.1: Rule-4-20-1.md
  - Rule 4.20.2: Rule-4-20-2.md
  - Rule 4.20.3: Rule-4-20-3.md
  - Rule 4.21.1: Rule-4-21-1.md
  - Rule 4.21.2: Rule-4-21-2.md
  - Rule 4.22.1: Rule-4-22-1.md
  - Rule 4.22.2: Rule-4-22-2.md
- Tables:
  - Rule 5.1.1: Rule-5-1-1.md
  - Rule 5.2.1: Rule-5-2-1.md
  - Rule 5.3.1: Rule-5-3-1.md
  - Rule 5.4.1: Rule-5-4-1.md
  - Rule 5.5.1: Rule-5-5-1.md
  - Rule 5.6.1: Rule-5-6-1.md
  - Rule 5.6.2: Rule-5-6-2.md
  - Rule 5.7.1: Rule-5-7-1.md
  - Rule 5.7.2: Rule-5-7-2.md
  - Rule 5.7.3: Rule-5-7-3.md
  - Rule 5.7.4: Rule-5-7-4.md
  - Rule 5.8.1: Rule-5-8-1.md
- Links:
  - Rule 6.1.1: Rule-6-1-1.md
  - Rule 6.1.2: Rule-6-1-2.md
  - Rule 6.1.3: Rule-6-1-3.md
  - Rule 6.1.4: Rule-6-1-4.md
  - Rule 6.1.5: Rule-6-1-5.md
  - Rule 6.2.1: Rule-6-2-1.md
  - Rule 6.2.2: Rule-6-2-2.md
  - Rule 6.2.3: Rule-6-2-3.md
  - Rule 6.2.4: Rule-6-2-4.md
  - Rule 6.2.5: Rule-6-2-5.md
  - Rule 6.3.1: Rule-6-3-1.md
  - Rule 6.3.2: Rule-6-3-2.md
  - Rule 6.3.3: Rule-6-3-3.md
  - Rule 6.3.4: Rule-6-3-4.md
  - Rule 6.3.5: Rule-6-3-5.md
  - Rule 6.4.1: Rule-6-4-1.md
  - Rule 6.4.2: Rule-6-4-2.md
  - Rule 6.4.3: Rule-6-4-3.md
  - Rule 6.4.4: Rule-6-4-4.md
  - Rule 6.4.5: Rule-6-4-5.md
  - Rule 6.5.1: Rule-6-5-1.md
- Scripts:
  - Rule 7.1.1: Rule-7-1-1.md
  - Rule 7.1.2: Rule-7-1-2.md
  - Rule 7.1.3: Rule-7-1-3.md
  - Rule 7.1.4: Rule-7-1-4.md
  - Rule 7.1.5: Rule-7-1-5.md
  - Rule 7.1.6: Rule-7-1-6.md
  - Rule 7.2.1: Rule-7-2-1.md
  - Rule 7.2.2: Rule-7-2-2.md
  - Rule 7.3.1: Rule-7-3-1.md
  - Rule 7.3.2: Rule-7-3-2.md
  - Rule 7.3.3: Rule-7-3-3.md
  - Rule 7.3.4: Rule-7-3-4.md
  - Rule 7.4.1: Rule-7-4-1.md
  - Rule 7.5.1: Rule-7-5-1.md
- Mandatory elements:
  - Rule 8.1.1: Rule-8-1-1.md
  - Rule 8.1.2: Rule-8-1-2.md
  - Rule 8.1.3: Rule-8-1-3.md
  - Rule 8.2.1: Rule-8-2-1.md
  - Rule 8.2.2: Rule-8-2-2.md
  - Rule 8.3.1: Rule-8-3-1.md
  - Rule 8.4.1: Rule-8-4-1.md
  - Rule 8.5.1: Rule-8-5-1.md
  - Rule 8.6.1: Rule-8-6-1.md
  - Rule 8.7.1: Rule-8-7-1.md
  - Rule 8.8.1: Rule-8-8-1.md
  - Rule 8.8.2: Rule-8-8-2.md
  - Rule 8.9.1: Rule-8-9-1.md
  - Rule 8.10.1: Rule-8-10-1.md
- Structuration of information:
  - Rule 9.1.1: Rule-9-1-1.md
  - Rule 9.1.2: Rule-9-1-2.md
  - Rule 9.1.3: Rule-9-1-3.md
  - Rule 9.1.4: Rule-9-1-4.md
  - Rule 9.2.1: Rule-9-2-1.md
  - Rule 9.2.2: Rule-9-2-2.md
  - Rule 9.3.1: Rule-9-3-1.md
  - Rule 9.3.2: Rule-9-3-2.md
  - Rule 9.3.3: Rule-9-3-3.md
  - Rule 9.4.1: Rule-9-4-1.md
  - Rule 9.5.1: Rule-9-5-1.md
  - Rule 9.6.1: Rule-9-6-1.md
  - Rule 9.6.2: Rule-9-6-2.md
- Presentation of information:
  - Rule 10.1.1: Rule-10-1-1.md
  - Rule 10.1.2: Rule-10-1-2.md
  - Rule 10.1.3: Rule-10-1-3.md
  - Rule 10.2.1: Rule-10-2-1.md
  - Rule 10.3.1: Rule-10-3-1.md
  - Rule 10.4.1: Rule-10-4-1.md
  - Rule 10.4.2: Rule-10-4-2.md
  - Rule 10.4.3: Rule-10-4-3.md
  - Rule 10.5.1: Rule-10-5-1.md
  - Rule 10.5.2: Rule-10-5-2.md
  - Rule 10.5.3: Rule-10-5-3.md
  - Rule 10.6.1: Rule-10-6-1.md
  - Rule 10.7.1: Rule-10-7-1.md
  - Rule 10.7.2: Rule-10-7-2.md
  - Rule 10.7.3: Rule-10-7-3.md
  - Rule 10.8.1: Rule-10-8-1.md
  - Rule 10.8.2: Rule-10-8-2.md
  - Rule 10.8.3: Rule-10-8-3.md
  - Rule 10.8.4: Rule-10-8-4.md
  - Rule 10.9.1: Rule-10-9-1.md
  - Rule 10.10.1: Rule-10-10-1.md
  - Rule 10.11.1: Rule-10-11-1.md
  - Rule 10.12.1: Rule-10-12-1.md
  - Rule 10.12.2: Rule-10-12-2.md
  - Rule 10.13.1: Rule-10-13-1.md
  - Rule 10.13.2: Rule-10-13-2.md
  - Rule 10.13.3: Rule-10-13-3.md
  - Rule 10.14.1: Rule-10-14-1.md
  - Rule 10.14.2: Rule-10-14-2.md
  - Rule 10.14.3: Rule-10-14-3.md
  - Rule 10.14.4: Rule-10-14-4.md
  - Rule 10.15.1: Rule-10-15-1.md
  - Rule 10.15.2: Rule-10-15-2.md
  - Rule 10.15.3: Rule-10-15-3.md
  - Rule 10.15.4: Rule-10-15-4.md
- Forms:
  - Rule 11.1.1: Rule-11-1-1.md
  - Rule 11.1.2: Rule-11-1-2.md
  - Rule 11.1.3: Rule-11-1-3.md
  - Rule 11.2.1: Rule-11-2-1.md
  - Rule 11.2.2: Rule-11-2-2.md
  - Rule 11.2.3: Rule-11-2-3.md
  - Rule 11.2.4: Rule-11-2-4.md
  - Rule 11.3.1: Rule-11-3-1.md
  - Rule 11.3.2: Rule-11-3-2.md
  - Rule 11.4.1: Rule-11-4-1.md
  - Rule 11.5.1: Rule-11-5-1.md
  - Rule 11.6.1: Rule-11-6-1.md
  - Rule 11.7.1: Rule-11-7-1.md
  - Rule 11.8.1: Rule-11-8-1.md
  - Rule 11.8.2: Rule-11-8-2.md
  - Rule 11.8.3: Rule-11-8-3.md
  - Rule 11.9.1: Rule-11-9-1.md
  - Rule 11.9.2: Rule-11-9-2.md
  - Rule 11.10.1: Rule-11-10-1.md
  - Rule 11.10.2: Rule-11-10-2.md
  - Rule 11.10.3: Rule-11-10-3.md
  - Rule 11.10.4: Rule-11-10-4.md
  - Rule 11.10.5: Rule-11-10-5.md
  - Rule 11.10.6: Rule-11-10-6.md
  - Rule 11.10.7: Rule-11-10-7.md
  - Rule 11.10.8: Rule-11-10-8.md
  - Rule 11.10.9: Rule-11-10-9.md
  - Rule 11.11.1: Rule-11-11-1.md
  - Rule 11.11.2: Rule-11-11-2.md
  - Rule 11.12.1: Rule-11-12-1.md
  - Rule 11.12.2: Rule-11-12-2.md
  - Rule 11.13.1: Rule-11-13-1.md
  - Rule 11.13.2: Rule-11-13-2.md
  - Rule 11.14.1: Rule-11-14-1.md
  - Rule 11.14.2: Rule-11-14-2.md
  - Rule 11.14.3: Rule-11-14-3.md
  - Rule 11.14.4: Rule-11-14-4.md
  - Rule 11.14.5: Rule-11-14-5.md
  - Rule 11.14.6: Rule-11-14-6.md
  - Rule 11.15.1: Rule-11-15-1.md
- Navigation:
  - Rule 12.1.1: Rule-12-1-1.md
  - Rule 12.2.1: Rule-12-2-1.md
  - Rule 12.2.2: Rule-12-2-2.md
  - Rule 12.3.1: Rule-12-3-1.md
  - Rule 12.3.2: Rule-12-3-2.md
  - Rule 12.4.1: Rule-12-4-1.md
  - Rule 12.4.2: Rule-12-4-2.md
  - Rule 12.4.3: Rule-12-4-3.md
  - Rule 12.5.1: Rule-12-5-1.md
  - Rule 12.5.2: Rule-12-5-2.md
  - Rule 12.5.3: Rule-12-5-3.md
  - Rule 12.6.1: Rule-12-6-1.md
  - Rule 12.6.2: Rule-12-6-2.md
  - Rule 12.6.3: Rule-12-6-3.md
  - Rule 12.7.1: Rule-12-7-1.md
  - Rule 12.8.1: Rule-12-8-1.md
  - Rule 12.9.1: Rule-12-9-1.md
  - Rule 12.10.1: Rule-12-10-1.md
  - Rule 12.10.2: Rule-12-10-2.md
  - Rule 12.10.3: Rule-12-10-3.md
  - Rule 12.10.4: Rule-12-10-4.md
  - Rule 12.11.1: Rule-12-11-1.md
  - Rule 12.11.2: Rule-12-11-2.md
  - Rule 12.11.3: Rule-12-11-3.md
  - Rule 12.11.4: Rule-12-11-4.md
  - Rule 12.12.1: Rule-12-12-1.md
  - Rule 12.13.1: Rule-12-13-1.md
  - Rule 12.13.2: Rule-12-13-2.md
  - Rule 12.14.1: Rule-12-14-1.md
- Consultation:
  - Rule 13.1.1: Rule-13-1-1.md
  - Rule 13.1.2: Rule-13-1-2.md
  - Rule 13.1.3: Rule-13-1-3.md
  - Rule 13.1.4: Rule-13-1-4.md
  - Rule 13.1.5: Rule-13-1-5.md
  - Rule 13.2.1: Rule-13-2-1.md
  - Rule 13.2.2: Rule-13-2-2.md
  - Rule 13.2.3: Rule-13-2-3.md
  - Rule 13.3.1: Rule-13-3-1.md
  - Rule 13.4.1: Rule-13-4-1.md
  - Rule 13.5.1: Rule-13-5-1.md
  - Rule 13.6.1: Rule-13-6-1.md
  - Rule 13.6.2: Rule-13-6-2.md
  - Rule 13.6.3: Rule-13-6-3.md
  - Rule 13.7.1: Rule-13-7-1.md
  - Rule 13.8.1: Rule-13-8-1.md
  - Rule 13.9.1: Rule-13-9-1.md
  - Rule 13.10.1: Rule-13-10-1.md
  - Rule 13.11.1: Rule-13-11-1.md
  - Rule 13.12.1: Rule-13-12-1.md
  - Rule 13.13.1: Rule-13-13-1.md
  - Rule 13.14.1: Rule-13-14-1.md
  - Rule 13.15.1: Rule-13-15-1.md
  - Rule 13.15.2: Rule-13-15-2.md
  - Rule 13.15.3: Rule-13-15-3.md
  - Rule 13.16.1: Rule-13-16-1.md
  - Rule 13.16.2: Rule-13-16-2.md
  - Rule 13.16.3: Rule-13-16-3.md
  - Rule 13.17.1: Rule-13-17-1.md
  - Rule 13.17.2: Rule-13-17-2.md

theme: readthedocs
repo_url: https://github.com/Tanaguru/Tanaguru
