---
asqatasun_debian_pkgs:
  - wget
  - bzip2
  - openjdk-7-jre
  - unzip
  - mysql-server
  - libmysql-java
  - python-mysqldb
  - libtomcat7-java
  - tomcat7
  - xvfb
  - libdbus-glib-1-2
  - mailutils
  - postfix

locale: 'en_US.UTF-8'

asqatasun_download_link: "http://download.asqatasun.org/asqatasun-latest.tar.gz"
# Asqatasun version that you want to install, get the full list of releases 
#by clicking in the release tab of the github main interface.
asqatasun_version: "asqatasun-4.1.0-SNAPSHOT"

# Go this link to find your desired ESR Firefox
# For 32-bit architecture
# http://download-origin.cdn.mozilla.net/pub/firefox/releases/31.4.0esr/linux-i686/
# For 64-bit architecture
# http://download-origin.cdn.mozilla.net/pub/firefox/releases/31.4.0esr/linux-x86_64/
# Default is en-US in our example
fixfox_esr_link: "http://download-origin.cdn.mozilla.net/pub/firefox/releases/31.4.0esr/linux-x86_64/en-US/firefox-31.4.0esr.tar.bz2"

# MySQL variables for Asqatasun
default_character_set: "utf8"
collation_server: "utf8_general_ci"
init_connect: "SET NAMES utf8"
character_set_server: "utf8"
mysql_max_allowed_packet: "64M"

asqatasun_parameters:
  db_name: 'asqatasun'
  db_user: 'asqatasun'
  db_password: 'asqaP4sswd'
  db_host: 'localhost'
  url: 'http://localhost:8080/asqatasun/'
  admin_email: 'admin@asqatasun.org'
  admin_passwd: 'myAsqaPassword'
